LIST_OF_CONTENTS_FAMILY = "//*[@id='toc']/ul//span[contains(text(),'Family')]"
LIST_OF_CONTENTS_MYTHOLOGY = "//*[@id='toc']/ul//span[contains(text(),'Mythology')]"
LIST_OF_CONTENTS_SOCIOLOGY = "//*[@id='toc']/ul//span[contains(text(),'In sociology')]"
LIST_OF_CONTENTS_HONOURS = "//*[@id='toc']/ul//span[contains(text(),'Honours')]"
LIST_OF_CONTENTS_REFERENCES = "//*[@id='toc']/ul//span[contains(text(),'References')]"
LIST_OF_CONTENTS_READING = "//*[@id='toc']/ul//span[contains(text(),'Further reading')]"
FAMILY_HEADING = "//*[@id='Family']"
MYTHOLOGY_HEADING = "//*[@id='Mythology']"
SOCIOLOGY_HEADING = "//*[@id='In_sociology']"
HONOURS_HEADING = "//*[@id='Honours']"
REFERENCES_HEADING = "//*[@id='References']"
READING_HEADING = "//*[@id='Further_reading']"
HYPERLINK_FAMILY = "//*[@id='toc']//ul/li[1]/a"
HYPERLINK_MYTHOLOGY = "//*[@id='toc']//ul/li[2]/a"
HYPERLINK_SOCIOLOGY = "//*[@id='toc']//ul/li[3]/a"
HYPERLINK_HONOURS = "//*[@id='toc']//ul/li[4]/a"
HYPERLINK_REFERENCES = "//*[@id='toc']//ul/li[5]/a"
HYPERLINK_READING = "//*[@id='toc']//ul/li[6]/a"
NIKE_LINK = "//*[@class='div-col']/ul/li/a[contains(text(),'Nike')]"
POPUP_TEXT = "//*[@class='mwe-popups-extract'][@href='/wiki/Nike_(mythology)']"
FAMILY_TREE = "//*[@id='Family_tree']"